---
openapi: 3.0.0
info:
  title: Simple Inventory API
  description: Collection of Keycloak API endpoints
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/theEpsilon/mindtastic_keycloak/1.0.0
  description: SwaggerHub API Auto Mocking
- url: /auth/realms/master/protocol/openid-connect
paths:
  /token:
    post:
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: addInventory
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/token_body'
      responses:
        "200":
          description: Successfully received access token
  /introspect:
    post:
      summary: Validate access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/introspect_body'
        required: true
      responses:
        "200":
          description: Successfully returned authentication result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
components:
  schemas:
    token_body:
      required:
      - client_id
      - grant_type
      - password
      - scope
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        client_id:
          type: string
        client_secret:
          type: string
        grant_type:
          type: string
        scope:
          type: string
    introspect_body:
      type: object
      properties:
        token:
          type: string
        client_id:
          type: string
        client_secret:
          type: string
    inline_response_200:
      type: object
      properties:
        active:
          type: string
          example: "false"
